=== IgnaxA/DATI_lab_2/schema/film_library.dtd
<!DOCTYPE filmLibrary [
    <!ELEMENT filmLibrary (film*)>
    <!ELEMENT film (title, genre+, producer*, composer*, actor*, date, gross?, cert, views?, lang)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT genre (#PCDATA)>
    <!ELEMENT producer (#PCDATA)>
    <!ELEMENT composer (#PCDATA)>
    <!ELEMENT actor (#PCDATA)>
    <!ELEMENT date (#PCDATA)>
    <!ELEMENT gross (#PCDATA)>
    <!ELEMENT cert (#PCDATA)>
    <!ELEMENT views (#PCDATA)>
    <!ELEMENT lang (#PCDATA)>
]>

=== IgnaxA/DATI_lab_2/film_data.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE filmLibrary SYSTEM "schema/film_library.dtd">

<filmLibrary>
    <film>
        <title>21 Jump Street</title>
        <genre>Buddy Cop</genre>
        <genre>Police Procedural</genre>
        <genre>Action</genre>
        <genre>Comedy</genre>
        <genre>Crime</genre>
        <producer>Phil Lord</producer>
        <producer>Christopher Miller</producer>
        <composer>Johnathon Cormier</composer>
        <composer>John Egli</composer>
        <actor>Jonah Hill</actor>
        <actor>Ice Cube</actor>
        <actor>Channing Tatum</actor>
        <actor>Brie Larson</actor>
        <actor>Dave Franco</actor>
        <actor>Rob Riggle</actor>
        <date>12.04.2012</date>
        <gross>201585556</gross>
        <cert>16+</cert>
        <views>4300000</views>
        <lang>En</lang>
    </film>

    <film>
        <title>Pulp Fiction</title>
        <genre>Dark Comedy</genre>
        <genre>Drug Crime</genre>
        <genre>Gangster</genre>
        <genre>Crime</genre>
        <genre>Drama</genre>
        <producer>Quentin Tarantino</producer>
        <composer>Jimmie Haskell</composer>
        <actor>John Travolta</actor>
        <actor>Uma Thurman</actor>
        <actor>Samuel L. Jackson</actor>
        <actor>Bruce Willis</actor>
        <actor>Quentin Tarantino</actor>
        <date>27.09.1995</date>
        <gross>213928762</gross>
        <cert>18+</cert>
        <views>83000000</views>
        <lang>En</lang>
    </film>

    <film>
        <title>Django Unchained</title>
        <genre>Dark Comedy</genre>
        <genre>Period Drama</genre>
        <genre>Western Epic</genre>
        <genre>Comedy</genre>
        <genre>Drama</genre>
        <genre>Western</genre>
        <producer>Quentin Tarantino</producer>
        <composer>Ainz Brainz Prasad</composer>
        <actor>Jamie Foxx</actor>
        <actor>Christoph Waltz</actor>
        <actor>Leonardo DiCaprio</actor>
        <actor>Quentin Tarantino</actor>
        <actor>Samuel L. Jackson</actor>
        <actor>Kerry Washington</actor>
        <date>17.01.2013</date>
        <gross>426076293</gross>
        <cert>18+</cert>
        <views>2300000</views>
        <lang>En</lang>
    </film>

    <film>
        <title>Schindler's List</title>
        <genre>Docudrama</genre>
        <genre>Epic</genre>
        <genre>Historical Epic</genre>
        <genre>Period Drama</genre>
        <genre>Biography</genre>
        <genre>Drama</genre>
        <genre>History</genre>
        <producer>Steven Spielberg</producer>
        <composer>Mimi Abers</composer>
        <actor>Liam Neeson</actor>
        <actor>Ben Kingsley</actor>
        <actor>Caroline Goodall</actor>
        <actor>Ralph Fiennes</actor>
        <date>21.05.1194</date>
        <gross>322161245</gross>
        <cert>16+</cert>
        <views>4300000</views>
        <lang>En</lang>
    </film>

    <film>
        <title>The Shawshank Redemption</title>
        <genre>Epic</genre>
        <genre>Prison Drama</genre>
        <genre>Drama</genre>
        <producer>Frank Darabont</producer>
        <composer>Thomas Newman</composer>
        <actor>Tim Robbins</actor>
        <actor>Morgan Freeman</actor>
        <actor>William Sadler</actor>
        <actor>Bob Guntoon</actor>
        <date>14.10.1994</date>
        <gross>29332133</gross>
        <cert>16+</cert>
        <views>3000000</views>
        <lang>En</lang>
    </film>

</filmLibrary>
